// boltConstants.js

export const ALL_BOLTS_REQUEST = 'ALL_BOLTS_REQUEST';
export const ALL_BOLTS_SUCCESS = 'ALL_BOLTS_SUCCESS';
export const ALL_BOLTS_FAIL = 'ALL_BOLTS_FAIL';

export const BOLT_DETAILS_REQUEST = 'BOLT_DETAILS_REQUEST';
export const BOLT_DETAILS_SUCCESS = 'BOLT_DETAILS_SUCCESS';
export const BOLT_DETAILS_FAIL = 'BOLT_DETAILS_FAIL';

export const BOLT_UPDATE_REQUEST = 'BOLT_UPDATE_REQUEST';
export const BOLT_UPDATE_SUCCESS = 'BOLT_UPDATE_SUCCESS';
export const BOLT_UPDATE_FAIL = 'BOLT_UPDATE_FAIL';

export const BOLT_DELETE_REQUEST = 'BOLT_DELETE_REQUEST';
export const BOLT_DELETE_SUCCESS = 'BOLT_DELETE_SUCCESS';
export const BOLT_DELETE_FAIL = 'BOLT_DELETE_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
