export const ALL_SCREWS_REQUEST = "ALL_SCREWS_REQUEST";
export const ALL_SCREWS_SUCCESS = "ALL_SCREWS_SUCCESS";
export const ALL_SCREWS_FAIL = "ALL_SCREWS_FAIL";

export const SCREW_DETAILS_REQUEST = "SCREW_DETAILS_REQUEST";
export const SCREW_DETAILS_SUCCESS = "SCREW_DETAILS_SUCCESS";
export const SCREW_DETAILS_FAIL = "SCREW_DETAILS_FAIL";

export const ADD_SCREW_REQUEST = "ADD_SCREW_REQUEST";
export const ADD_SCREW_SUCCESS = "ADD_SCREW_SUCCESS";
export const ADD_SCREW_FAIL = "ADD_SCREW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
